### PR TITLE
Highlight operators

### PR DESCRIPTION
**Pull request by xeluxee**
Previously:
grop1

Now (I made delimiters gray because there was too much orange):
grop2

### CODE REVIEW

**Comment by sQVe** [comment]
@ellisonleao I find this change problematic since it applies the same color for operators and comments. It looks nice on the examples provided in the PR but on `typescript` it looks like this:

image

I've seen other examples where the this new highlighting hurts readability.

**Comment by BarrensZeppelin** [comment]
For python array delimiters are now highlighted in gray along with parentheses which is not great for readability.

**Comment by ellisonleao** [comment]
@sQVe is the old way just better then? sorry guys i am not using the theme right now as much as I've wanted to and i am just trying to keep it using the same conventions as the community version with some improvements using treesitter. If you have a better suggestion can you open a new PR please?

**Comment by sQVe** [comment]
@ellisonleao I actually override this with: https://github.com/sQVe/dotfiles/commit/db536bdf287fc15f243f3824fecc96edcc9d3811#diff-bafa32261574bdfd4ed74f3f4de0f4c3ba5063d5c4e18c870c21534fbc40b663R16, which I feel aligns better with the original gruvbox.

Also, feel free to reach out if you're looking for help maintaining.

**Comment by xeluxee** [comment]
@sQVe you're right, we could
- use orange operators and gray only in some languages like C and C++
- revert this PR back
- Make delimiters orange keeping operator orange
- Make delimiters use a different color, like cyan or purple (idk what could be the best color)

I didn't noticed this issue since I use [rainbow brackets](https://github.com/p00f/nvim-ts-rainbow)

**Comment by eeeXun** [comment]
I suggest use white(or Fg1) for delimiter, which is similar to origin gruvbox.
```diff
diff --git a/lua/gruvbox/base.lua b/lua/gruvbox/base.lua
index c5ef634..eaa05ec 100644
--- a/lua/gruvbox/base.lua
+++ b/lua/gruvbox/base.lua
@@ -249,7 +249,7 @@ local base_group = lush(function()
     Typedef {GruvboxYellow},
     SpecialChar {GruvboxRed},
     Tag {GruvboxAquaBold},
-    Delimiter {GruvboxGray},
+    Delimiter {GruvboxFg1},
     Comment {fg = gray, gui = styles.italic_comments},
     Debug {GruvboxRed},
     Underlined {fg = blue, gui = styles.underline},
```

**Comment by timbedard** [comment]
My vote is for `Delimiter {GruvboxFg2}`.

**Comment by xeluxee** [comment]
> My vote is for `Delimiter {GruvboxFg2}`.

What about `GruvboxFg3`? IMHO `GruvboxFg2` looks too close to normal foreground

**Comment by timbedard** [comment]
> What about `GruvboxFg3`? IMHO `GruvboxFg2` looks too close to normal foreground

Also fine.

**Comment by xeluxee** [comment]
And what about operators? Is it better to keep them orange only for C and C++?

**Pull request merged**
