### PR TITLE
feat: add EndOfBuffer highlight group

### LINKED ISSUE #336: Add option to hide the end of buffer icon (~)
### Is your feature request related to a problem? Please describe.

I would like to have an option in the config to hide the  end of buffer icons easier.
Currently, this could be done by override the highlight EndOfBuffer to have the fg the same color as the background.

### Describe the solution you'd like

This is my proposed solution..

```lua
    opts = {
      show_end_of_buffer = true,
}
```

We can have an additional option like above to achieve this easier

### PR DESCRIPTION
**Pull request by nguyenanhhao221**
Close #336

### CODE REVIEW

**Review by ellisonleao — CHANGES_REQUESTED** [review]
hey @nguyenanhhao221 thanks for the PR. Can you remove the config option and just add the color group linking to `NonText` please:
```lua
-- ...
EndOfBuffer = { link = "NonText" },
-- ...
```

**Comment by nguyenanhhao221** [comment]
@ellisonleao thanks for the suggestion, but I'm a little confuse because when I try to link it with `NonText`, I still see the ~ icon as the image below. 

Screenshot 2024-05-18 at 01 05 55

If I try like this, it will be hidden but without the config option the icon will always be hidden and can only be show back when override the highlight group. 

```lua
EndOfBuffer = { link = "GruvboxBg0" }
```

**Comment by ellisonleao** [comment]
> If I try like this, it will be hidden but without the config option the icon will always be hidden and can only be show back when override the highlight group.

that's the idea no? i don't want to add a new config just for that use case where you can override the color for your personal needs.

**Comment by nguyenanhhao221** [comment]
> > If I try like this, it will be hidden but without the config option the icon will always be hidden and can only be show back when override the highlight group.
> 
> that's the idea no? i don't want to add a new config just for that use case where you can override the color for your personal needs.

I see, thanks for the clarification 👍

**Pull request merged**
