### PR TITLE
refactor(gruvbox): remove lush dependency

### PR DESCRIPTION
**Pull request by mhdahmad**

### CODE REVIEW

**Comment by mhdahmad** [comment]
Hi @ellisonleao 
I hope you are doing well

This PR has multiple changes to current mainstream, lush.nvim can be removed now. plus since this colorscheme is for Neovim 0.5+ only I've also removed filte types highlight groups and make colorscheme dependent on Treesitter only since this what must be I think...

the last mentioned changes also reduced load time from ~14ms to ~5ms (depending on my machine).
I guess this is a better move to keep maintaining this theme and to keep up with gruvbox-community for example. Thanks for your work on this theme bro

We love Gruvbox after all :heart:

**Comment by ellisonleao** [comment]
wow, thanks for that PR. I will probably need some time to review it, but glad it's here.

**Comment by ellisonleao** [comment]
hey @mhdahmad as a initial request, can you please use https://github.com/JohnnyMorganz/StyLua as the formatter? there's already a stylua.toml config with the desired style

**Comment by mhdahmad** [comment]
Hi @ellisonleao ,
 Actually as a formatter I've been using Stylua too, now the previous commit used the configs file who is in the repo.

**Comment by ellisonleao** [comment]
thanks @mhdahmad , now can you try to fix the current conflicts please? i had to fix some issues with markdown highlights and I've also went back to vimscript in the airline plugin.

**Pull request closed without merging**
