### PR TITLE
Resolve #99

### LINKED ISSUE #99: use `vim.api.nvim_set_hl()` instead of `vim.cmd[[]]` calls

### PR DESCRIPTION
**Pull request by ellisonleao**

### CODE REVIEW

**Comment by roland-rollo** [comment]
I tested it, and it works without errors. Not sure if this commit is somehow useful https://github.com/neovim/neovim/commit/cb18545253259af339957316ab8361fb0cca48e5
Can I do some test to help you, even without knowing lua?

**Comment by ellisonleao** [comment]
@roland-rollo are you on 0.6.1 ? i am having issues on making this work in the stable version, just got it working in the nightly one. About the new flags, i am not seeing the colorschemes using it yet, but thanks for the heads up.

**Comment by roland-rollo** [comment]
I'm on git compiled version (I compile it everyday). This things will not work with 0.6.1 as i remember from reddit discussion. 0.6.2 will have it or 0.7 version and there are one or two things they still need to clarify.

**Comment by ellisonleao** [comment]
@roland-rollo cool, i will wait the new stable version then before pushing this

**Comment by stvhuang** [comment]
I made some fixes #108, which renames `inverse` to `reverse` in color attribute maps.

According to help docs (`:h nvim_set_hl()`), `inverse` is an alias to `reverse`, but I have no idea why `inverse` raises errors.

I tested the fixes on neovim 0.7-stable and 0.8-dev+3.

**Comment by stvhuang** [comment]
Sorry, `reverse` gives no errors but also seems not working. I closed the PR #108.

**Pull request merged**
