### PR TITLE
indent-blankline.nvim support

### PR DESCRIPTION
**Pull request by franciscozdo**
I have added the groups used by [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim).

### CODE REVIEW

**Comment by franciscozdo** [comment]
Before my change:
Screenshot from 2023-09-30 10-51-45

After my change:
Screenshot from 2023-09-30 10-51-56

**Comment by ellisonleao** [comment]
thanks, will include that in #280

**Comment by polyzen** [comment]
indent-blankline recently released v3 which changed the highlight groups, they now have `IblIndent`, `IblWhitespace`, and `IblScope`.

https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3#highlights

**Comment by ellisonleao** [comment]
FYI i've just installed the new version and highlights seems fine, so i don't think we need to make anything right now 
image

**Pull request closed without merging**
