### PR TITLE
made it darker

### PR DESCRIPTION
**Pull request by seirennn**
i like black

### CODE REVIEW

**Comment by seirennn** [comment]
black

**Comment by seirennn** [comment]
s

**Review by seirennn — COMMENTED** [review]
w

**Comment by darkangel-ua** [comment]
Why do think that your personal preferences should be for everyone?

**Comment by sQVe** [comment]
> Why do think that your personal preferences should be for everyone?

Especially when the color theme supports overriding.

**Comment by ellisonleao** [comment]
hey @seirennn you can override colors and groups with your own personal preference. Please check the README file on how to proper do this

**Comment by seirennn** [comment]
> hey @seirennn you can override colors and groups with your own personal preference. Please check the README file on how to proper do this

Oh shit how are you here, I'm so sorry for disturbing y'all, this is my first time using GitHub😭😭😭 I'm totally embarassed reading the replies of my commits, or whatever so sorry for disturbing and thank you😭🥹

**Comment by seirennn** [comment]
> Why do think that your personal preferences should be for everyone?

Nooo, I had no idea it would change for everyone, heck I had no idea that's how commit messages worked, I had a different idea of how all theses works, I didn't mean to be rude or mannerless, rlly new to GitHub so pls excuse me😭😭🙏

**Comment by ellisonleao** [comment]
@seirennn no worries man, feel free to open an issue or a discussion topic if you are stuck on something

**Pull request closed without merging**
