### PR TITLE
Use backgrounds only for diff mode

### PR DESCRIPTION
**Pull request by Niverton**
Hello, here is my attempt at adding new background colors for the diff mode highlights to (re)fix issue #105.
I mixed the original colors for light and dark with each background colors for every contrast to stay true to the original palette. I mainly use dark hard mode so I'm not sure about the readability of the other modes, but I'm happy with the result. Hopefully my go at it will at least motivate other attempts!

This project and the original theme deserve all the love they can get, thank you for the lua port.

# Screenshots
### Soft
dark_soft
### Classic
dark_normal
### Hard
dark_hard
### Soft
light_soft
### Classic
light_normal
### Hard
light_hard

### CODE REVIEW

**Comment by eeeXun** [comment]
I think the `DiffAdd` and `DiffChange` are too similar. Hard to recognize

**Comment by darkangel-ua** [comment]
I find existing variant vivid and easy to read. Not sure this need to be changed...

**Comment by eeeXun** [comment]
Someone may need syntax highlight in diff mode. So why not?
But I think its better have it configurable like https://github.com/ellisonleao/gruvbox.nvim/pull/228

**Comment by darkangel-ua** [comment]
The change is much more that just _syntax highlight preservation_ from what I see. 
And I completely agree that if we want a set of variants we should make it configurable.

**Comment by Niverton** [comment]
> I think the `DiffAdd` and `DiffChange` are too similar. Hard to recognize

I made the yellow a bit more vibrant so we can see it better next to green; I think with the blue background on the side it's different enough from the Add to be okay.
Dark mode with high contrast:
dark_hard2

> Someone may need syntax highlight in diff mode. So why not? But I think its better have it configurable like #228

I made this PR because diffing large code blocks with black text on a bright green background is hard on the eye. Added the config option, disabled by default. Although someone already using the theme might miss a new option it might be better to not change existing workflow.

> The change is much more that just _syntax highlight preservation_ from what I see.

Not sure what you mean by that, as my initial PR only changed the diff highlight groups? It does indeed just keep the the syntax highlighting intact, and of course only changing the background is the only way to achieve that without losing the diff colors.

**Comment by eeeXun** [comment]
> I made the yellow a bit more vibrant so we can see it better next to green; I think with the blue background on the side it's different enough from the Add to be okay. Dark mode with high contrast: dark_hard2

Cool! Much better.

**Comment by ellisonleao** [comment]
hey guys i will close this one so we can open a proper discussion about the diff issue. I would GLADLY ASK you to try the [community version](https://github.com/gruvbox-community/gruvbox) first (which is the version we've created this repo), then check if the SAME ISSUE happens over there. I know treesitter is not fully supported there but it seems the problem is always about the same highlight groups. Can we do that please?

**Pull request closed without merging**
